FROM ubuntu:xenial
RUN apt-get update
RUN apt-get -y install curl
RUN curl -o /tmp/puppet6-release-xenial.deb https://apt.puppetlabs.com/puppet6-release-xenial.deb
RUN dpkg -i /tmp/puppet6-release-xenial.deb
RUN apt-get update

# install puppet-agent (comes with puppet parser validate, which is what we want) and puppet-lint
RUN apt-get -y update && apt-get -y install puppet-agent puppet-lint

RUN cp /opt/puppetlabs/bin/puppet /bin/puppet